### ISSUE TITLE
Column 'name' in where clause is ambiguous

### ISSUE THREAD

**Issue by bastienuh** [nenes25/prestashop_customerautogroups#5]
Hi,

I have an error with the module, on Prestashop 1.7.7.4, when I try to make a search on the name of a rule :

```
Column 'name' in where clause is ambiguous<br /><br /><pre>SELECT SQL_CALC_FOUND_ROWS b.*, a.* , IF ( a.`condition_type` = 1 , 'Customer','Customer Address') AS condition_type_name,gl.name AS group_name FROM `ps_autogroup_rule` a LEFT JOIN `ps_autogroup_rule_lang` b ON (b.`id_rule` = a.`id_rule` AND b.`id_lang` = 1) LEFT JOIN `ps_group_lang` gl ON (gl.`id_group` = a.`id_group` AND gl.`id_lang` = 1) WHERE 1 AND `name` LIKE '%rueil%' ORDER BY a.id_rule ASC LIMIT 0, 50</pre>
at line 769 in file classes/db/Db.php
```

The stack trace :

- DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
- DbCore->query - [line 613 - classes/db/Db.php] - [1 Arguments]
- DbCore->executeS - [line 3263 - classes/controller/AdminController.php] - [3 Arguments]
- AdminControllerCore->getList - [line 2378 - classes/controller/AdminController.php] - [1 Arguments]
- AdminControllerCore->renderList - [line 153 - modules/customerautogroups/controllers/admin/rules.php]
- RulesController->renderList - [line 2184 - classes/controller/AdminController.php]
- AdminControllerCore->initContent - [line 306 - classes/controller/Controller.php]
- ControllerCore->run - [line 518 - classes/Dispatcher.php]
- DispatcherCore->dispatch - [line 93 - admin/index.php]

I have made a fresh install of the module, in case of I made a mistake somewhere, but the bug is still there.
Moreover, the module is not working correctly, so I guess it's linked to this problem...

Do you know how to fix it?

Thanks!

**Comment by bastienuh** [comment]
In my opinion, the only thing to do is to replace :
```sql
WHERE 1 AND `name` LIKE '%rueil%'
```

by :
```sql
WHERE 1 AND `ps_autogroup_rule_lang.name` LIKE '%rueil%'
```

But I can't find where :-(

**Comment by nenes25** [comment]
Hello,
The issue is fixed.
Thanks for the report :smile: 

Regards,

**Comment by ssoaresp** [comment]
Hi, trying to install this module in 1.7.8.7, any help please:

Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "rulesController" from the global namespace.
Did you forget a "use" statement?

  at classes/controller/Controller.php:233
  at ControllerCore::getController('rulesController')
     (classes/Dispatcher.php:510)
  at DispatcherCore->dispatch()
     (stqgvsfspbe3580m/index.php:93)
